services:
  # 1. The Database Service
  db:
    image: postgres:15-alpine
    container_name: ministore
    restart: always
    environment:
      POSTGRES_DB: ministore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Maps container port to localhost:5432 (for your local DB tools)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ministore"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Your Application Service
  app:
    build: .
    container_name: ministore-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ENC_SALT: "$$2a$$12$$dFAdnFuzyCPTDbt9hYG6Ce"
      DB_USR: postgres
      DB_PWD: root

volumes:
  postgres_data:
